### PR TITLE
reloads when going back to a non-chaplinized page

### PR DESCRIPTION
**Pull request by evantarrh**
helps prepare for partial chaplinization of mobile. see [this pull request](https://github.com/Everlane/everlane.com/pull/1111)

### CODE REVIEW

**Comment by jeffmicklos** [comment]
@evantarrh wow you are amazing – welcome home.

**Comment by thenanyu** [comment]
Whens the last time we pull from upstream?

**Comment by jeffmicklos** [comment]
@thenanyu, it's been awhile but, as ever, nothing material has changed with Chaplin in that time – only docs updates.

**Comment by evantarrh** [comment]
Refactored the mobile chaplin routing PR to not need this fix :blush:

**Comment by mtthgn** [comment]
@thenanyu I'm gonna re-open this PR. The fix in `mobile.coffee` actually breaks in some pretty bad ways (infinite refresh, etc.).

I'd like to test on staging with build against this change in Chaplin to see if we experience similar issues.

What are your thoughts?

**Comment by mtthgn** [comment]
cc @jeffmicklos  ^^^^

**Comment by jeffmicklos** [comment]
@mtthgn Chaplin can be compiled locally and just dropped into your local repo and pushed to staging if you wanna test this change... Well, I guess the easiest thing would be for you to change where Chaplin gets required in to reference a file that you monkey patch with this code

**Pull request closed without merging**
